M48
; DRILL file {KiCad 9.0.7} date 2026-02-11T18:54:03-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-11T18:54:03-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X5.3406Y-4.0059
X5.4193Y-4.0059
X5.498Y-4.0059
T2
X5.2579Y-4.0059
X5.5807Y-4.0059
T3
X5.4193Y-3.6339
M30
