M48
; DRILL file {KiCad 7.0.6} date Tue Aug  1 21:42:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-01T21:42:17-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0591
%
G90
G05
T1
X5.27Y-3.8
X5.57Y-3.8
T2
X5.3413Y-4.0
X5.42Y-4.0
X5.4987Y-4.0
T3
X5.2586Y-4.0
X5.5814Y-4.0
T0
M30
